name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ## setup
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          path: .
      - name: Check AWS Installation
        run: aws --version
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: npm install

      ## Deploy to Production
      - name: Deploy to Production
        run: echo 'deploying to production...'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}