name: Deploy Staging Link
on:
  pull_request:
    types: ['opened', 'synchronize', 'closed']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          path: .
      - name: Check AWS Installation # automatically installed on github hosted images
        run: aws --version
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          path: .
      - name: Install NPM dependencies
        run: npm install
      - name: Run NPM package
        run: npm test
      - run: echo ${{github.event.action}}
      - name: Deploy Staging
        if: github.event.action == 'opened'
        run: echo 'deploying to staging...'
      - name: Update Staging
        if: github.event.action == 'synchronize'
        run: echo 'Updating staging...'
      - name: Delete Staging
        if: github.event.action == 'closed'
        run: echo $GITHUB_REF
  # deploy-staging:
  #   if: github.event == 'opened'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Branch
  #       uses: actions/checkout@v2
  #       with:
  #         path: .
  #     - name: 
